# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisUi(object):

    def setupUi(self, JarvisUi):

        JarvisUi.setObjectName("JarvisUi")
        JarvisUi.resize(1413, 940)
        self.centralwidget = QtWidgets.QWidget(JarvisUi)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(0, 0, 501, 171))
        self.bg_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.bg_2.setText("")
        self.bg_2.setObjectName("bg_2")
        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(960, 10, 451, 381))
        self.bg_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.bg_3.setText("")
        self.bg_3.setObjectName("bg_3")


        self.Gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_1.setGeometry(QtCore.QRect(10, 0, 471, 151))
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("Database/G.U.I material/gui 1 (5).gif"))
        self.Gif_1.setScaledContents(True)
        self.Gif_1.setObjectName("Gif_1")
        self.Gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_2.setGeometry(QtCore.QRect(930, 30, 451, 381))
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("Database/G.U.I material/gui 1 (3).gif"))
        self.Gif_2.setScaledContents(True)
        self.Gif_2.setObjectName("Gif_2")


        self.bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.bg_4.setGeometry(QtCore.QRect(490, 170, 421, 501))
        self.bg_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.bg_4.setText("")
        self.bg_4.setObjectName("bg_4")


        self.Gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_3.setGeometry(QtCore.QRect(500, 180, 401, 481))
        self.Gif_3.setText("")
        self.Gif_3.setPixmap(QtGui.QPixmap("Database/G.U.I material/gui 1 (4).gif"))
        self.Gif_3.setScaledContents(True)
        self.Gif_3.setObjectName("Gif_3")


        self.bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.bg_5.setGeometry(QtCore.QRect(0, 170, 491, 401))
        self.bg_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.bg_5.setText("")
        self.bg_5.setObjectName("bg_5")


        self.Gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_4.setGeometry(QtCore.QRect(10, 160, 461, 371))
        self.Gif_4.setText("")
        self.Gif_4.setPixmap(QtGui.QPixmap("Database/G.U.I material/gui 1 (7).gif"))
        self.Gif_4.setScaledContents(True)
        self.Gif_4.setObjectName("Gif_4")


        self.bg_6 = QtWidgets.QLabel(self.centralwidget)
        self.bg_6.setGeometry(QtCore.QRect(960, 420, 451, 361))
        self.bg_6.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.bg_6.setText("")
        self.bg_6.setObjectName("bg_6")


        self.Gif_5 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_5.setGeometry(QtCore.QRect(960, 390, 451, 331))
        self.Gif_5.setText("")
        self.Gif_5.setPixmap(QtGui.QPixmap("Database/G.U.I material/jarvis 9.webp"))
        self.Gif_5.setScaledContents(True)
        self.Gif_5.setObjectName("Gif_5")


        self.bg_7 = QtWidgets.QLabel(self.centralwidget)
        self.bg_7.setGeometry(QtCore.QRect(1060, 710, 351, 231))
        self.bg_7.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.bg_7.setText("")
        self.bg_7.setObjectName("bg_7")


        self.Gif_6 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_6.setGeometry(QtCore.QRect(1030, 680, 311, 251))
        self.Gif_6.setText("")
        self.Gif_6.setPixmap(QtGui.QPixmap("Database/G.U.I material/gui 1 (9).gif"))
        self.Gif_6.setScaledContents(True)
        self.Gif_6.setObjectName("Gif_6")


        self.bg_8 = QtWidgets.QLabel(self.centralwidget)
        self.bg_8.setGeometry(QtCore.QRect(0, 570, 401, 371))
        self.bg_8.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.bg_8.setText("")
        self.bg_8.setObjectName("bg_8")


        self.Gif_7 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_7.setGeometry(QtCore.QRect(10, 560, 361, 281))
        self.Gif_7.setText("")
        self.Gif_7.setPixmap(QtGui.QPixmap("Database/G.U.I material/gui 1 (8).gif"))
        self.Gif_7.setScaledContents(True)
        self.Gif_7.setObjectName("Gif_7")
        self.bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.bg_1.setGeometry(QtCore.QRect(-10, 0, 1421, 951))
        self.bg_1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.bg_1.setText("")
        self.bg_1.setObjectName("bg_1")
        self.bg_9 = QtWidgets.QLabel(self.centralwidget)
        self.bg_9.setGeometry(QtCore.QRect(500, 620, 341, 121))
        self.bg_9.setText("")
        self.bg_9.setPixmap(QtGui.QPixmap("Database/G.U.I material/jarvis date.jpg"))
        self.bg_9.setScaledContents(True)
        self.bg_9.setObjectName("bg_9")

        
        self.text_button_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_button_1.setGeometry(QtCore.QRect(710, 750, 331, 111))
        self.text_button_1.setStyleSheet("background-color: Transparent;\n"
"border-radius: None;")
        self.text_button_1.setObjectName("text_button_1")
        self.pushButton_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Start.setGeometry(QtCore.QRect(370, 780, 291, 71))
        self.pushButton_Start.setStyleSheet("font: 20pt \"Old English Text MT\";\n"
"background-color: Transparent;\n"
"color: rgb(255, 170, 127);")
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.bg_11 = QtWidgets.QLabel(self.centralwidget)
        self.bg_11.setGeometry(QtCore.QRect(360, 750, 311, 141))
        self.bg_11.setText("")
        self.bg_11.setPixmap(QtGui.QPixmap("Database/G.U.I material/jarvis button 1.jpg"))
        self.bg_11.setScaledContents(True)
        self.bg_11.setObjectName("bg_11")
        self.bg_10 = QtWidgets.QLabel(self.centralwidget)
        self.bg_10.setGeometry(QtCore.QRect(690, 750, 311, 141))
        self.bg_10.setText("")
        self.bg_10.setPixmap(QtGui.QPixmap("Database/G.U.I material/jarvis button 1.jpg"))
        self.bg_10.setScaledContents(True)
        self.bg_10.setObjectName("bg_10")
        self.pushButton_Quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Quit.setGeometry(QtCore.QRect(700, 760, 291, 111))
        self.pushButton_Quit.setStyleSheet("background-color: Transparent;\n"
"font: 20pt \"Old English Text MT\";\n"
"color: rgb(255, 170, 127);")
        self.pushButton_Quit.setObjectName("pushButton_Quit")
        self.bg_1.raise_()
        self.bg_5.raise_()
        self.bg_2.raise_()
        self.bg_3.raise_()
        self.Gif_1.raise_()
        self.Gif_2.raise_()
        self.bg_4.raise_()
        self.Gif_3.raise_()
        self.Gif_4.raise_()
        self.bg_6.raise_()
        self.Gif_5.raise_()
        self.bg_7.raise_()
        self.Gif_6.raise_()
        self.bg_8.raise_()
        self.Gif_7.raise_()
        self.bg_9.raise_()
        self.text_button_1.raise_()
        self.bg_11.raise_()
        self.pushButton_Start.raise_()
        self.bg_10.raise_()
        self.pushButton_Quit.raise_()
        JarvisUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(JarvisUi)
        QtCore.QMetaObject.connectSlotsByName(JarvisUi)

    def retranslateUi(self, JarvisUi):
        _translate = QtCore.QCoreApplication.translate
        JarvisUi.setWindowTitle(_translate("JarvisUi", "MainWindow"))
        self.pushButton_Start.setText(_translate("JarvisUi", "START"))
        self.pushButton_Quit.setText(_translate("JarvisUi", "QUIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUi = QtWidgets.QMainWindow()
    ui = Ui_JarvisUi()
    ui.setupUi(JarvisUi)
    JarvisUi.show()
    sys.exit(app.exec_())
